# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/clojure:1.11.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deps.edn" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: clojure -P

      # run tests!
      - run: clojure -T:build test

      - save_cache:
          paths:
            - ~/.m2
            - .cpcache
          key: v1-dependencies-{{ checksum "deps.edn" }}
